const std = @import("std");
const mem = std.mem;
const zig = std.zig;
const ArrayList = std.ArrayList;
const Build = std.Build;
const Io = std.Io;

pub fn build(b: *Build) void {
    _ = b; // stub
}

/// Format a nesting `depth` as 4-space indentation.
pub const DepthF = struct {
    depth: usize,

    pub fn format(self: @This(), writer: *Io.Writer) Io.Writer.Error!void {
        for (0..self.depth) |_| //
            try writer.writeAll("    ");
    }
};

/// Asset Entry
const Entry = struct {
    name: []const u8,
    kind: Io.File.Kind,
};

/// Asset/Resouce Generation Config
pub const Config = struct {
    /// Directory for Assets/Resources.
    dir: []const u8 = "assets",
    /// Generated module name (written into `dir`).
    name: []const u8 = "assets.zig",
    /// Directory and File names to skip
    skip_names: []const []const u8 = &.{},
    /// Directory and File prefixes to skip
    skip_prefixes: []const []const u8 = &.{},
    /// Directory and File suffixes to skip
    skip_suffixes: []const []const u8 = &.{ ".zig" },
};

/// Generate an Asset/Resource Module based on the provided `config`
pub fn genModule(b: *Build, config: Config) *Build.Module {
    var aw: Io.Writer.Allocating = .init(b.allocator);
    defer aw.deinit();
    aw.writer.writeAll("// Generated by `gram` — do not edit.\n\n") catch @panic("Write Failed");
    var dir = b.build_root.handle.openDir(b.graph.io, config.dir, .{ .iterate = true }) catch @panic("Cannot open assets dir");
    defer dir.close(b.graph.io);
    walkDir(b, &aw.writer, dir, "", 0, config);
    const mod_path = b.fmt("{s}/{s}", .{ config.dir, config.name });
    b.build_root.handle.writeFile(b.graph.io, .{ .sub_path = mod_path, .data = aw.written() }) catch @panic("Cannot write generated module");
    return b.createModule(.{ .root_source_file = b.path(mod_path) });
}

/// Recursively emit `pub const` declarations for every entry in `dir`.
///
/// - Each subdirectory becomes a nested `pub const <name> = struct { ... };`.
/// - Each file becomes a `pub const <name> = @embedFile("<path>");`.
///
/// `prefix` is the path from the assets root to `dir`, with a trailing slash
/// (empty at the root); it builds the `@embedFile` argument, which resolves
/// relative to the generated module sitting in the assets root. `depth` drives
/// indentation, and `skip` is the generated module's own name so it never
/// embeds itself.
fn walkDir(
    b: *Build,
    w: *Io.Writer,
    dir: Io.Dir,
    prefix: []const u8,
    depth: usize,
    config: Config,
) void {
    var entries: ArrayList(Entry) = .empty;
    var iter = dir.iterate();
    iterLoop: while (iter.next(b.graph.io) catch @panic("Asset iteration failed")) |entry| {
        for (config.skip_names) |skip| {
            if (mem.eql(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        for (config.skip_prefixes) |skip| {
            if (mem.startsWith(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        for (config.skip_suffixes) |skip| {
            if (mem.endsWith(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        if ( //
            entry.name.len == 0 or //
            entry.name[0] == '.' or //
            (entry.kind != .file and entry.kind != .directory) //
        ) //
            continue;
        entries.append(b.allocator, .{
            .name = b.dupe(entry.name),
            .kind = entry.kind,
        }) catch @panic("OOM");
    }
    mem.sort(
        Entry,
        entries.items,
        {},
        struct {
            fn lt(_: void, a: Entry, c: Entry) bool { return mem.lessThan(u8, a.name, c.name); }
        }.lt,
    );
    const indent: DepthF = .{ .depth = depth };
    for (entries.items) |entry| switch (entry.kind) {
        .directory => {
            w.print("{f}pub const {f} = struct {{\n", .{ indent, zig.fmtId(entry.name) }) catch @panic("write failed");
            var sub = dir.openDir(b.graph.io, entry.name, .{ .iterate = true }) catch @panic("cannot open subdirectory");
            defer sub.close(b.graph.io);
            walkDir(b, w, sub, b.fmt("{s}{s}/", .{ prefix, entry.name }), depth + 1, config);
            w.print("{f}}};\n", .{ indent }) catch @panic("write failed");
        },
        .file => {
            const embed_path = b.fmt("{s}{s}", .{ prefix, entry.name });
            w.print(
                "{f}pub const {f}: []const u8 = @embedFile(\"{f}\");\n",
                .{ indent, zig.fmtId(entry.name), zig.fmtString(embed_path) },
            ) catch @panic("write failed");
        },
        else => unreachable,
    };
}
