const std = @import("std");
const mem = std.mem;
const zig = std.zig;
const ArrayList = std.ArrayList;
const Build = std.Build;
const Io = std.Io;

pub fn build(b: *Build) void {
    _ = b; // stub
}

/// Format a nesting `depth` as 4-space indentation.
pub const DepthF = struct {
    depth: usize,

    pub fn format(self: @This(), writer: *Io.Writer) Io.Writer.Error!void {
        for (0..self.depth) |_| //
            try writer.writeAll("    ");
    }
};

/// Asset Entry
const Entry = struct {
    name: []const u8,
    kind: Io.File.Kind,
};

/// Asset/Resouce Generation Config
pub const Config = struct {
    /// Directory for Assets/Resources.
    dir: GenInfo = .auto,
    /// Generated module name (written into `dir`).
    name: GenInfo = .auto,
    /// Directory and File names to skip
    skip_names: []const []const u8 = &.{},
    /// Directory and File prefixes to skip
    skip_prefixes: []const []const u8 = &.{},
    /// Directory and File suffixes to skip
    skip_suffixes: []const []const u8 = &.{ ".zig" },

    pub const GenInfo = union(enum) {
        auto,
        raw: []const u8,
    };
};

/// Generate an Asset/Resource Module based on the provided `config`
pub fn genModule(b: *Build, config: Config) *Build.Module {
    const dir_path: []const u8 = switch (config.dir) {
        .auto => path: {
            for ([_][]const u8{ "assets", "resources" }) |name| {
                var dir = b.build_root.handle.openDir(b.graph.io, name, .{ .iterate = true }) catch continue;
                dir.close(b.graph.io);
                break :path name;
            } //
            else @panic("Could not find `assets` or `resources` directory");
        },
        .raw => |raw| raw,
    };
    const mod_name: []const u8 = switch (config.name) {
        .auto => b.fmt("{s}.zig", .{ dir_path }),
        .raw => |raw| raw: {
            if (mem.endsWith(u8, raw, ".zig")) //
                break :raw raw;
            break :raw b.fmt("{s}", .{ raw });
        },
    };
    var dir = b.build_root.handle.openDir(b.graph.io, dir_path, .{ .iterate = true }) catch @panic("Could not open `assets` or `resources` directory");
    defer dir.close(b.graph.io);
    var aw: Io.Writer.Allocating = .init(b.allocator);
    defer aw.deinit();
    aw.writer.writeAll("// Generated by `gram` — do not edit.\n\n") catch @panic("Write Failed");
    walkDir(b, &aw.writer, dir, "", 0, config);
    const mod_path = b.fmt("{s}/{s}", .{ dir_path, mod_name });
    b.build_root.handle.writeFile(b.graph.io, .{ .sub_path = mod_path, .data = aw.written() }) catch @panic("Could not write generated module");
    return b.createModule(.{ .root_source_file = b.path(mod_path) });
}

/// Recursively emit `pub const` declarations for every entry in `dir`.
///
/// - Each subdirectory becomes a nested `pub const <name> = struct { ... };`.
/// - Each file becomes a `pub const <name> = @embedFile("<path>");`.
fn walkDir(
    b: *Build,
    w: *Io.Writer,
    dir: Io.Dir,
    /// Path from the assets root to `dir`.
    prefix: []const u8,
    /// Directory depth. Drives indentation for nested declarations.
    depth: usize,
    /// Skip Information
    config: Config,
) void {
    var entries: ArrayList(Entry) = .empty;
    var iter = dir.iterate();
    iterLoop: while (iter.next(b.graph.io) catch @panic("Asset iteration failed")) |entry| {
        for (config.skip_names) |skip| {
            if (mem.eql(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        for (config.skip_prefixes) |skip| {
            if (mem.startsWith(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        for (config.skip_suffixes) |skip| {
            if (mem.endsWith(u8, entry.name, skip)) //
                continue :iterLoop;
        }
        if ( //
            entry.name.len == 0 or //
            entry.name[0] == '.' or //
            (entry.kind != .file and entry.kind != .directory) //
        ) //
            continue;
        entries.append(
            b.allocator,
            .{
                .name = b.dupe(entry.name),
                .kind = entry.kind,
            },
        ) catch @panic("OOM");
    }
    mem.sort(
        Entry,
        entries.items,
        {},
        struct {
            fn lt(_: void, a: Entry, c: Entry) bool {
                return mem.lessThan(u8, a.name, c.name);
            }
        }.lt,
    );
    const indent: DepthF = .{ .depth = depth };
    for (entries.items) |entry| switch (entry.kind) {
        .directory => {
            w.print("{f}pub const {f} = struct {{\n", .{ indent, zig.fmtId(entry.name) }) catch @panic("Write Failed");
            var sub = dir.openDir(b.graph.io, entry.name, .{ .iterate = true }) catch @panic("Could not open subdirectory");
            defer sub.close(b.graph.io);
            walkDir(b, w, sub, b.fmt("{s}{s}/", .{ prefix, entry.name }), depth + 1, config);
            w.print("{f}}};\n", .{ indent }) catch @panic("Write Failed");
        },
        .file => {
            const embed_path = b.fmt("{s}{s}", .{ prefix, entry.name });
            w.print(
                "{f}pub const {f}: []const u8 = @embedFile(\"{f}\");\n",
                .{
                    indent,
                    zig.fmtId(entry.name),
                    zig.fmtString(embed_path),
                },
            ) catch @panic("Write Failed");
        },
        else => {},
    };
}
